#!/bin/bash

pkill -9 gnome-shell

mkdir -p /run/user/32011 || true
chmod 755 -R /run/user || true
chown manjaro:manjaro -R /run/user/32011 || true

# when X starts up at boot theres this bug where the first thing that runs on it doesnt output anything on the screen so we need to run it once, kill it and run it again.
exec su - manjaro -c "sh -c \"unset TERM && unset QT_QPA_PLATFORM && unset QT_WAYLAND_DISABLE_WINDOWDECORATION && unset MOZ_ENABLE_WAYLAND && XDG_SESSION_TYPE=x11 EGL_PLATFORM=x11 DISPLAY=:0 XDG_RUNTIME_DIR=/run/user/32011 GDK_GL=gles GDK_SCALE=2 QT_AUTO_SCREEN_SET_FACTOR=0 QT_SCALE_FACTOR=2 QT_FONT_DPI=96 dbus-run-session gnome-shell --replace\"" &

sleep 3

pkill -9 gnome-shell

while true
do
    if [ $(pidof gnome-shell) ]; then
       true
    else
        exec su - manjaro -c "sh -c \"unset TERM && unset QT_QPA_PLATFORM && unset QT_WAYLAND_DISABLE_WINDOWDECORATION && unset MOZ_ENABLE_WAYLAND && export $(dbus-launch) && export XDG_RUNTIME_DIR="/run/user/32011" export DBUS_SESSION_BUS_ADDRESS="unix:path=${XDG_RUNTIME_DIR}/bus" && export DBUS_SESSION_BUS_ADDRESS=/run/user/32011/bus && XDG_SESSION_TYPE=x11 EGL_PLATFORM=x11 DISPLAY=:0 XDG_RUNTIME_DIR=/run/user/32011 GDK_GL=gles GDK_SCALE=2 QT_AUTO_SCREEN_SET_FACTOR=0 QT_SCALE_FACTOR=2 QT_FONT_DPI=96 dbus-run-session gnome-shell --replace\"" &
    fi
    exec su - manjaro -c "sh -c \"unset TERM && unset QT_QPA_PLATFORM && unset QT_WAYLAND_DISABLE_WINDOWDECORATION && unset MOZ_ENABLE_WAYLAND && XDG_SESSION_TYPE=x11 EGL_PLATFORM=x11 DISPLAY=:0 XDG_RUNTIME_DIR=/run/user/32011 DISPLAY=:0 xbindkeys -f /etc/X11/xbindkeysrc\""
    sleep 5s
done
