#!/bin/bash

pkill -9 gnome-shell

mkdir -p /run/user/32011 || true
chmod 755 -R /run/user || true
chown manjaro:manjaro -R /run/user/32011 || true

# when X starts up at boot theres this bug where the first thing that runs on it doesnt output anything on the screen so we need to run it once, kill it and run it again.
exec su - manjaro -c "sh -c \"unset TERM && XDG_SESSION_TYPE=x11 DISPLAY=:0 XDG_RUNTIME_DIR=/run/user/32011 GDK_GL=gles dbus-run-session gnome-shell --replace\"" &

sleep 3

pkill -9 gnome-shell

while true
do
    if [ $(pidof gnome-shell) ]; then
       true
    else
        exec su - manjaro -c "sh -c \"unset TERM && XDG_SESSION_TYPE=x11 DISPLAY=:0 XDG_RUNTIME_DIR=/run/user/32011 GDK_GL=gles dbus-run-session gnome-shell --replace\"" &
    fi
    sleep 5s
done
